### ISSUE TITLE
Needs updating!

### ISSUE THREAD

**Issue by firtoz** [firtoz/GPT-Shell#17]
The project is a bit out of date.

Please do this:
- update the openai usage to use the new chatgpt API instead of text davinci 3
- mark `lib` as ignored folder
- test it in replit and make sure it still works
- use node_modules with yarn config
- use pm2 - see https://github.com/firtoz/GPT-Shell/pull/15/files 

I had a start at this branch, but didn't have a chance to test it, so, feel free to base your code on it:
https://github.com/firtoz/GPT-Shell/compare/update-project?expand=1

**Comment by firtoz** [comment]
Bounty: $50! Claim at https://app.bountysource.com/issues/122778418-needs-updating

**Comment by mamonet** [comment]
https://github.com/bountysource/core/issues/1586

**Comment by firtoz** [comment]
> [bountysource/core#1586](https://github.com/bountysource/core/issues/1586)

Oh crap. What do you recommend as the alternative?

**Comment by mamonet** [comment]
Sorry, I don't have any experience with alternatives. My comment was just a warning to not post any further bounties at Bountysource because they are not paying hunters anymore.

**Comment by firtoz** [comment]
I guess I will withdraw it if possible and post on an alternative

**Comment by mamonet** [comment]
Bountysource is a shell company by now, pretty sure your funds are stuck. They no longer respond to anyone including their biggest backer. IBM is engaging its legals now.

**Comment by firtoz** [comment]
Well, that sucks. Should have done more research. Thanks for letting me know at least!

**Comment by firtoz** [comment]
I will see if PayPal can help with refund

**Comment by firtoz** [comment]
Note to bounty claimers: if you complete it, let me know here, I will send the bounty to you directly

**Comment by techcoderx** [comment]
There aren't a lot of breaking changes as the libraries still work

#18

**Comment by firtoz** [comment]
Fixed via #19 - bounty resolved off platform

**Comment by firtoz** [comment]
@mamonet a little success :D 
![Screenshot_20230708_042105_Fastmail](https://github.com/firtoz/GPT-Shell/assets/108406948/d177cd96-9a99-41a2-8539-ceb6751481a9)

**Comment by mamonet** [comment]
I'm really glad to hear that. Apparently, PayPal was able to discern their scam business. 
$50 not that much but at least Bountysource doesn't seize your funds as they don't seem to get enough after embezzling thousands of dollars from other backers and bounty hunters.

**Comment by mamonet** [comment]
@firtoz Do you mind if I referred this issue to other backers so they can do the same within 180 days of their PayPal transition?

**Comment by firtoz** [comment]
All good, go ahead @mamonet
