### ISSUE TITLE
Using Fine Tuned Models?

### ISSUE THREAD

**Issue by scottrblock** [firtoz/GPT-Shell#8]
Hey, just came across this project, looks really cool, great work! I stumbled upon it because I want to build something that allows people to [fine tune](https://beta.openai.com/docs/guides/fine-tuning) a `text-davinci-003` model, and chat with it.

I'm just starting to poke around `gpt-shell`, but it looks like `ModelInfio.ts` could be extended to allow a fine-tuned model. Not sure exactly the best way to handle the frontend, but ideally a user would be able to specify a custom model string somewhere in discord?

Is this on your radar at all?

**Comment by firtoz** [comment]
Hi @scottrblock thank you for the interest. Yes the code could be extended indeed to allow fine tuned models, but I believe at this point it would be prohibitively expensive to use fine tuned models because of how they are priced.

If there is some funding, it would be great to experiment with that though.

**Comment by scottrblock** [comment]
ya agreed it would be pretty expensive. 

do you have thoughts on uploading the fine tuned training data inside gpt-shell vs. only allowing a way to point at an already fine-tuned model?

**Comment by firtoz** [comment]
If fine tuning becomes cheap enough, ideally it should have a fine tuned model per conversation, where people can upload anything to it

For simple experimentation, it should also allow pre fine tuned model inputs too, that would probably be the fastest way to start hacking around tbh :)

**Comment by scottrblock** [comment]
One way to get around high costs of openai is to use an open source model such as https://github.com/EleutherAI/gpt-neox. I see in the code there are paths to supporting different models. Are you planning to implement any of that soon?

**Comment by firtoz** [comment]
Apologies I missed this one! It's not in the plans soon but I think it will be fun to experiment with neox or more open models. If they do a good enough job with conversations it will definitely be beneficial to switch over to them, first it all to reduce costs.

**Comment by scottrblock** [comment]
sounds good @firtoz, will continue watching this project! I am not looking to dive into all of this right now, so I think this issue can be closed.
